package edu.monash.fit2081.srv2actv;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

public static String broadcastFilter="monash.fit2081.randomService";
    //Reference to the textview where we show the random number that is generated by the service
    TextView randomTv;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        randomTv = findViewById(R.id.random_id);
        // lets register the broadcast receiver handler that will be invoked each time the service
        // sends a new random number
        // The broadcast receiver is listening(i.e. waiting) using filter
        registerReceiver(new ServiceBroadcastHandler(), new IntentFilter(broadcastFilter));

        // this intent is used to start the service
        Intent intent = new Intent(this, RandomService.class);
        startService(intent);
    }


    // this inner class is the broadcast receiver handler that will catch
    // all messages (announcements or broadcasts) from the service
    class ServiceBroadcastHandler extends BroadcastReceiver {

        // this method will be invoked each time the services sends a new broadcast
        @Override
        public void onReceive(Context context, Intent intent) {
            // get the message and update the UI
            int value = intent.getIntExtra("randomValueKey", 0);
            randomTv.setText(String.valueOf(value));
        }
    }
}
